# This is not a complete list of requirements.
# These are just the packages that need to be installed by conda
# before natcap.invest can be installed.
channels:
- conda-forge
dependencies:
- python==3.8.10
- gdal==3.1.2
- numpy
- shapely<2.0.0
- rtree
- pip:
  - setuptools_scm
  - sphinx
  - git-lfs
  - natcap.invest

