# This is not a complete list of requirements.
# These are just the packages that need to be installed by conda
# before natcap.invest can be installed.
channels:
- conda-forge
- defaults
dependencies:
- gdal
- numpy
- shapely
- rtree
