# This is not a complete list of requirements.
# These are just the packages that need to be installed by conda
# before natcap.invest can be installed.
channels:
- conda-forge
- nodefaults
dependencies:
- pip
- gdal==3.1.2
- pip:
  - -r requirements.txt

